disabling boxed test if version xdist newer than 2.5.0
pytest-dev/pytest-cov pull request #565
Opened 2022-11-15 10:24 UTC by Chedi

Newer version of xdist  (> 2.5.0) have removed the boxed option.

[xdist changelog](https://github.com/pytest-dev/pytest-xdist/blob/master/CHANGELOG.rst#pytest-xdist-250-2021-12-10)

2022-12-03 13:30 UTC, cclauss approved these changes

2023-02-28 11:13 UTC, hugovk requested changes

2023-02-28 11:13 UTC, hugovk commented on tests/test_pytest_cov.py
> +                    reason="--boxed option was removed in version 2.5.0")
It was deprecated in [2.5.0](https://github.com/pytest-dev/pytest-xdist/blob/master/CHANGELOG.rst#pytest-xdist-250-2021-12-10) and removed in [3.0.2](https://github.com/pytest-dev/pytest-xdist/blob/master/CHANGELOG.rst#pytest-xdist-302-2022-10-25).

```suggestion
@pytest.mark.skipif('tuple(map(int, xdist.__version__.split("."))) >= (3, 0, 2)',
                    reason="--boxed option was removed in version 3.0.2")
```

2023-05-24 00:19 UTC, ionelmc commented
Rebased in master. Will release in 4.1 later today if no objections.

2023-05-24 00:19 UTC, closed without merging