Add .git-blame-ignore-revs
pytest-dev/pytest-cov pull request #640
Opened 2024-04-04 11:27 UTC by akx

This makes GitHub (and other tools that support this file, or any Git client with `git config blame.ignoreRevsFile .git-blame-ignore-revs` set) ignore the large reformatting/automatic commits, to make blame inspection easier.

2024-04-04 11:36 UTC, Pierre-Sassoulas approved these changes

2024-05-27 16:51 UTC, akx commented
@Pierre-Sassoulas Added the file to `MANIFEST.in` too to make the `check` Tox step pass.

2024-05-27 18:52 UTC, Pierre-Sassoulas requested changes
76fb2a6cb2c4a4a788a5b62710848daf9c8fb7ce could be removed from the git blame but not ff3fdd8039bb11e93d7a5b06a32091d58e97bfbf which introduce some non formatting changes (remove six, maybe others) and some unsafe fixes from ruff. I'm pretty sure the migration from ``os.path`` to ``pathlib`` is not automated either (I initially thought it was because of this MR, until I actually tried and the deception was strong).

2024-08-26 09:38 UTC, webknjaz commented
I'd argue it's not just a formatting change but a functional one. F-strings are more performant so it's more of an enhancement rather than formatting. Usually only patches that are solely formatting are ignored. Bits that are useful for git paleontology aren't supposed to be hidden...

2024-08-26 09:52 UTC, Pierre-Sassoulas reviewed
I'm not sure what's the point of `.git-blame-ignore-revs` in Manifest.in : after packaging git is not involved anymore, right ? So if f-strings removed from git blame are not consensual, there would be nothing left of this MR if we also remove that 😅

2024-08-26 12:41 UTC, akx commented
> I'm not sure what's the point of `.git-blame-ignore-revs` in Manifest.in

Without it there, `check-manifest` would fail.

2024-08-26 12:50 UTC, Pierre-Sassoulas commented
What is check-manifest and why does it fail ? manifest.in is linked to python packaging and does not involve git, right ?

2024-08-26 13:51 UTC, ionelmc commented
check-manifest is used to make sure the sdist contains all the source files and nothing is missing. Maybe this new file needs to be an exclude in there.

But alas, I am not sure who is this file for. I will not use it - I prefer to see everything in the gitblame, and jumping back a commit is pretty easy enough (it's just one button in github anyway).
![image](https://github.com/user-attachments/assets/0b49dbba-0a58-40cb-a7e1-6252343d1b1a)

2024-10-09 14:56 UTC, webknjaz commented
> check-manifest is used to make sure the sdist contains all the source files and nothing is missing. Maybe this new file needs to be an exclude in there.
> 
> But alas, I am not sure who is this file for. I will not use it - I prefer to see everything in the gitblame, and jumping back a commit is pretty easy enough (it's just one button in github anyway). ![image](https://private-user-images.githubusercontent.com/129501/361456339-0b49dbba-0a58-40cb-a7e1-6252343d1b1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0ODU5NTEsIm5iZiI6MTcyODQ4NTY1MSwicGF0aCI6Ii8xMjk1MDEvMzYxNDU2MzM5LTBiNDlkYmJhLTBhNTgtNDBjYi1hN2UxLTYyNTIzNDNkMWIxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQxNDU0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMmM4YWI2N2Y3NTY1OTI2NGI4ZTdiM2I0MzUwNmUyY2RkNGUwMDJmOGJhYjkyNWJjZDRkZmZkNTM3OTM4YWI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZPP89BctQiJAhV6xpeDRQ8Z1s_Ys8se0id-Jo-9aSAI)

@ionelmc this file is picked up by GitHub automatically, and it hides the listed commits from blame, unlike local Git invocations where that needs to be configured.

2024-10-09 14:57 UTC, webknjaz commented
> check-manifest is used to make sure the sdist contains all the source files and nothing is missing. Maybe this new file needs to be an exclude in there.

Have you considered using `setuptools-scm` which auto-includes everything Git-tracked into sdists?

2025-03-29 15:06 UTC, webknjaz commented
@ionelmc would you be open to integrating `setuptools-scm`?

2025-03-31 10:19 UTC, ionelmc commented
@webknjaz I am not opposed in principle. I use it on projects with C extensions where it's useful to have uniquely versioned pre-release distributions. But on this project I don't see the value to change an already working packaging setup. As a matter of fact I only see myself responding to bug reports caused by such a change.

Anyway, regarding this ignore-revs change - I don't want it. I simply don't trust even myself to not introduce behavior changes in formatting commits.

2025-03-31 10:19 UTC, closed without merging